# Generated by Django 5.1.7 on 2025-04-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
