# Generated by Django 5.1.7 on 2025-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_learningmaterial_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
