# Generated by Django 5.1.7 on 2025-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_learningmaterial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
