# Generated by Django 5.1.7 on 2025-04-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_learningmaterial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='video',
            name='chapter_name',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='lesson_icons/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.lesson'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
