# Generated by Django 5.1.7 on 2025-04-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_learningmaterial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='name',
        ),
    ]
