# Generated by Django 5.1.7 on 2025-04-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_learningmaterial_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
