# Generated by Django 5.1.7 on 2025-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='material_type',
            field=models.CharField(blank=True, choices=[('Syllabus', 'Syllabus'), ('Notes', 'Notes'), ('Old Question', 'Old Question'), ('Gamefication', 'Gamefication')], max_length=255, null=True),
        ),
    ]
