# Generated by Django 5.0.4 on 2025-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_lessonreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
