# Generated by Django 5.1.7 on 2025-04-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(choices=[('background', 'Background Only'), ('scene', 'Background with Objects and Text'), ('quiz', 'Quiz Frame')], default='background', max_length=20)),
                ('background_image', models.FileField(blank=True, null=True, upload_to='game_backgrounds/')),
                ('previous_frame', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_frame', to='game.frame')),
            ],
        ),
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the object (e.g., Newton, Apple, Tree)', max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='game_objects/')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='game.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Dialogue text spoken by the object')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='game.frame')),
                ('game_object', models.ForeignKey(help_text='Who speaks this text', on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='game.gameobject')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Quiz question')),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='game.frame')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.quiz')),
            ],
        ),
    ]
