# Generated by Django 5.1.7 on 2025-04-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '__first__'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='course.chapter'),
        ),
    ]
