# Generated by Django 5.1.7 on 2025-04-02 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_frame_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='next_frame',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_frame_relation', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='previous_frame',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_frame_relation', to='game.frame'),
        ),
    ]
