# Generated by Django 5.1.7 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_background_remove_frame_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='game.quizoption'),
        ),
    ]
