# Generated by Django 5.1.7 on 2025-04-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_quizoption_quiz_quiz_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='next_frame',
        ),
    ]
