# Generated by Django 5.1.7 on 2025-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_frame_next_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the answer', null=True),
        ),
    ]
