# Generated by Django 5.0.4 on 2025-04-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_learningmaterial_material_type'),
        ('game', '0008_quizoption_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='chapter',
        ),
        migrations.AddField(
            model_name='frame',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='course.lesson'),
        ),
    ]
