# Generated by Django 5.1.7 on 2025-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='frame',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the frame', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='frame',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='animation',
            field=models.CharField(blank=True, help_text='Animation of the object', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='animation_direction',
            field=models.CharField(blank=True, help_text='Direction of the animation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='animation_speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gameobject',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='position_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='position_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
