# Generated by Django 5.1.7 on 2025-04-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_dialogue_height_dialogue_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameobject',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_objects', to='game.frame'),
        ),
    ]
